version: '3'
services:
  octoprint:
    image: docker.io/octoprint/octoprint:latest
    ports:
      - '5000:80'
    privileged: true
    volumes:
      - ~/.config/octoprint:/octoprint/octoprint
      - ../docker-klipper:/klipper-config
      - ./scripts:/data/scripts
      - /dev:/dev
      - /tmp:/tmp
      - /opt/vc:/opt/vc
      - ~/.config/octoprint-arduino:/root/.arduino15
    environment:
      CAMERA_DEV: '/dev/v4l/by-id/usb-Microsoft_Microsoft®_LifeCam_HD-5000-video-index0'
      MJPEG_STREAMER_AUTOSTART: 'true'
      #MJPEG_STREAMER_INPUT: 'input_uvc.so -y -n -r 640x480'
      MJPEG_STREAMER_INPUT: 'input_uvc.so -y -n -r 1280x720'
      PYTHONPATH: '/usr/lib/python2.7/site-packages'
    restart: unless-stopped
  klipper:
    # image: dudeofawesome/klipper:latest
    build:
      context: '../docker-klipper'
      dockerfile: 'Dockerfile'
    privileged: true
    volumes:
      - '../klipper-config:/klipper-config'
      - '../klipper-config/.config:/klipper/.config'
      - '/dev:/dev'
      - '/tmp:/tmp'
    restart: unless-stopped

