version: '3'
services:
  octoprint:
    image: nunofgs/octoprint:alpine
    ports:
      - '5000:80'
    #devices:
      #- /dev/ttyACM0:/dev/ttyACM0
      #- /dev/video0:/dev/video0
    cap_add:
      - SYS_PTRACE
    volumes:
      - /usr/local/etc/docker-octoprint:/data
      - /dev/bus:/dev/bus:ro
      - /dev/serial:/dev/serial:ro
    environment:
      CAMERA_DEV: '/dev/video0'
      MJPEG_STREAMER_AUTOSTART: 'true'
      MJPEG_STREAMER_INPUT: '-y -n -r 640x480'

