version: '3'
services:
  traefik:
    image: docker.io/library/traefik:v2.5
    command:
      - '--api.dashboard=true' # enables the web UI
      - '--api.insecure=true' # enables the web UI
      - '--ping=true' # enables healthcheck route
      - '--providers.docker' # tell Traefik to listen to docker
      - '--providers.docker.exposedbydefault=false' # do not expose containers unless explicitly told so
      - '--providers.docker.network=docker-compose-octoprint_traefik-net' # set traefik's network
      - '--log.level=DEBUG' # set log level
      - '--accesslog=true' # enable access logs
      - '--accessLog.filePath=/var/log/access.log' # set access log path
      # - '--accessLog.format='
      - '--providers.file.directory=/traefik/dynamic' # use dynamic config files
      - '--entryPoints.http.address=:80' # listen on 80
      - '--entryPoints.https.address=:443' # listen on 443
      - '--entryPoints.traefik.address=:8080' # listen on 8080
      # redirect http to https
      - '--entryPoints.http.http.redirections.entryPoint.to=https'
      - '--entryPoints.http.http.redirections.entryPoint.scheme=https'
      - '--serversTransport.insecureSkipVerify=true' # disable certificate verification for load balance endpoints
    # user: '${USER_ID}:${GROUP_ID}'
    ports:
      - '8008:80' # HTTP port
      - '8008:80/udp' # HTTP port
      - '4443:443' # HTTPS port
      - '4443:443/udp' # HTTPS port
      - '3000:8080' # dashboard
      - '3000:8080/udp' # dashboard
    networks:
      - traefik-net
    volumes:
      # TODO: don't pass in the socket. start here https://doc.traefik.io/traefik/providers/docker/#docker-api-access
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./files/ssl:/etc/ssl-certs:ro
      - ./files/traefik/dynamic:/traefik/dynamic
      - /var/log/traefik:/var/log
    healthcheck:
      test: 'traefik healthcheck --ping'
    restart: 'unless-stopped'
  
  fluidd:
    image: 'docker.io/cadriel/fluidd:latest'
    labels:
      traefik.enable: 'true'
      traefik.http.routers.fluidd.rule: 'PathPrefix(`/`)'
      traefik.http.routers.fluidd.tls: 'true'
      traefik.http.services.fluidd.loadbalancer.server.port: '80'
    ports:
      - '5000:80'
    networks:
      - 'traefik-net'
    volumes:
      - '../klipper-config:/klipper-config'
      - '/var/log/klippy.log:/var/log/klippy.log'
      - '/dev:/dev'
      - '/tmp:/tmp'
    # environment:
      # JPEG_STREAM_HOST: ''
      # JPEG_STREAM_PORT: ''
    depends_on: 
      - 'moonraker'
    restart: 'unless-stopped'
  moonraker:
    # image: 'docker.io/mkuf/moonraker:nightly'
    build:
      context: '../moonraker'
      dockerfile: 'Dockerfile'
    labels:
      traefik.enable: 'true'
      traefik.http.routers.moonraker.rule: 'PathPrefix(`/websocket`,`/printer`,`/api`,`/access`,`/machine`,`/server`)'
      traefik.http.routers.moonraker.tls: 'true'
      traefik.http.services.moonraker.loadbalancer.server.port: '7125'
    volumes:
      - './files/moonraker/moonraker.conf:/opt/cfg/moonraker.conf'
      - '/var/lib/docker-moonraker:/home/klippy/.moonraker_database'
      - '../klipper-config:/klipper-config'
      - '/var/lib/gcode_files:/gcode_files'
      - '/var/log/klippy.log:/var/log/klippy.log'
      - '/tmp:/tmp'
      - '/opt/vc:/opt/vc'
    ports:
      - '7125:7125'
    networks:
      - 'klipper-net'
      - 'traefik-net'
    command: >-
      --configfile=/opt/cfg/moonraker.conf
      --logfile=/var/log/moonraker.log
      --nologfile
    depends_on: 
      - 'klipper'
    restart: 'unless-stopped'
  klipper:
    # image: dudeofawesome/klipper:latest
    build:
      context: '../docker-klipper'
      dockerfile: 'Dockerfile'
    privileged: yes
    volumes:
      - '../klipper-config:/klipper-config:ro'
      - '../klipper-config/printer.cfg:/klipper-config/printer.cfg'
      - '../klipper-config/.config:/klipper/.config'
      - '/var/lib/gcode_files:/gcode_files'
      - '/var/log/klippy.log:/var/log/klippy.log'
      - '/dev:/dev'
      - '/tmp:/tmp'
    entrypoint: >-
      python /klipper/klippy/klippy.py
      "/klipper-config/printer.cfg"
      --logfile="/var/log/klippy.log"
      --api-server="/tmp/klippy_uds.sock"
    # command: '--api-server="/tmp/klippy_uds.sock"'
    networks:
      - 'klipper-net'
    restart: 'unless-stopped'
networks:
  traefik-net:
  klipper-net:
